[NCCL][Symmetric Memory] Fix groupName in IntraNodeComm (#180809)
* [NCCL][Symmetric Memory] Fix groupName in IntraNodeComm (#180663)

This PR fixes:
```
RuntimeError: Could not resolve the process group registered under the name
```
in `python test/distributed/test_c10d_nccl.py CommTest.test_intra_node_comm_all_reduce`.

Just FYI: A quite similar error was attempted to be fixed in #177700, however the refactor #176506 partially fixed the original one by lazy pg registration, though missed the process group name.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/180663
Approved by: https://github.com/Skylion007

(cherry picked from commit 168339d2d7810d26263f85173eb1aae6b306f5ca)

* Add parameterization to test_intra_node_comm_all_reduce

Parameterized the test for intra-node communication to allow for custom group names.

---------

Co-authored-by: Aidyn-A <aidyn.b.aitzhan@gmail.com>
Co-authored-by: Aidyn-A <31858918+Aidyn-A@users.noreply.github.com>